translate_task:
  description: >
    {sentence}를 영어에서 한국어로 오역없이 번역해.
  expected_output: >
    깔끔하게 번역된 문장. 이름이나 장소는 작은따옴표로 감싸
  agent: translator_agent

retranslate_task:
  description: >
    {sentence}를 영어에서 일본어로 오역없이 번역해.
  expected_output: >
    깔끔하게 번역된 문장. 이름이나 장소는 작은따옴표로 감싸
  agent: translator_agent